#!/bin/sh
CMD="./gradlew clean test"
# Check if we actually have commits to push
echo "Before pushing steps:"
echo "Checking commits ..."
commits=`git log @{u}..`
if [ -z "$commits" ]; then
echo "No commits found"
exit 0;
fi
echo "Running tests ..."
$CMD
RESULT=$?
if [ $RESULT -ne 0 ]; then
echo "Tests failed $CMD"
 exit 1;
fi
exit 0;
