adb shell am broadcast ^
  -n com.github.syedahmedjamil.pushernotif.debug/com.google.firebase.iid.FirebaseInstanceIdReceiver ^
  -a "com.google.android.c2dm.intent.RECEIVE" ^
  --es "interest" "test" ^
  --es "category" "test" ^
  --es "date" "test_date" ^
  --es "title" "test_title" ^
  --es "body" "test_body" ^
  --es "subtext" "test_subtext" ^
  --es "link" "https://github.com" ^
  --es "image" "https://user-images.githubusercontent.com/20031479/181098478-7a170d22-94f0-43f7-8f69-b9d47873d42f.png"