name: Dev - Pull Request

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK And Gradle
        uses: ./.github/actions/setup-jdk-gradle
        with:
          cache-read-only: false
          
      - name: Get Google Services Json
        env:
          CERTIFICATE_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $GOOGLE_SERVICES_JSON

      - name: Upload Unit Test Report
        uses: actions/upload-artifact@v3
        with:
          name: file
          path: app/google-services.json

      # - name: a1
      #   run: ls -la

      # - name: a2
      #   run: less app/google-services.json
          
      # - name: Run Unit Test
      #   run: ./gradlew test

      # - name: Upload Unit Test Report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: unit-tests-report
      #     path: build/reports/unitTests
