name: Main - Push

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'README.md'
    branches: [ "main" ]
    
  workflow_dispatch:
  
jobs:
  upload-signed-release-firebase-app-distribution:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup JDK And Gradle
        uses: ./.github/actions/setup-jdk-gradle
        with:
          cache-read-only: false        
        
      - name: Get Google Services Json
        env:
          CERTIFICATE_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > app/google-services.json

      - name: Get App Release Signing Key
        env:
          CERTIFICATE_BASE64: ${{ secrets.APP_RELEASE_SIGNING_KEY }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > app/pusher-notif-release-key.jks

      - name: Get Firebase App Distribution Key
        env:
          CERTIFICATE_BASE64: ${{ secrets.FIREBASE_APP_DISTRIBUTION_KEY }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > app/main-firebase-app-distribution-admin-key.json

      - name: Assemble Signed Release Apk
        run: ./gradlew assembleRelease -PversionCode=${{ github.run_number }}

      - name: Generate Release Notes From Last Commit
        run: git log -1 > app/release-notes.txt

      - name: Upload To Firebase App Distribution
        run: ./gradlew appDistributionUploadRelease
